export const COUNTRY_LIST: { code: string; name: string }[] = [
  { code: "AF", name: "AFGHANISTAN" },
  { code: "AL", name: "ALBANIA" },
  { code: "DZ", name: "ALGERIA" },
  { code: "AS", name: "AMERICAN SAMOA" },
  { code: "AD", name: "ANDORRA" },
  { code: "AO", name: "ANGOLA" },
  { code: "AI", name: "ANGUILLA" },
  { code: "AG", name: "ANTIGUA" },
  { code: "AR", name: "ARGENTINA" },
  { code: "AM", name: "ARMENIA" },
  { code: "AW", name: "ARUBA" },
  { code: "AU", name: "AUSTRALIA" },
  { code: "AT", name: "AUSTRIA" },
  { code: "AZ", name: "AZERBAIJAN" },
  { code: "BS", name: "BAHAMAS" },
  { code: "BH", name: "BAHRAIN" },
  { code: "BD", name: "BANGLADESH" },
  { code: "BB", name: "BARBADOS" },
  { code: "BY", name: "BELARUS" },
  { code: "BE", name: "BELGIUM" },
  { code: "BZ", name: "BELIZE" },
  { code: "BJ", name: "BENIN" },
  { code: "BM", name: "BERMUDA" },
  { code: "BT", name: "BHUTAN" },
  { code: "BO", name: "BOLIVIA" },
  { code: "XB", name: "BONAIRE" },
  { code: "BA", name: "BOSNIA AND HERZEGOVINA" },
  { code: "BW", name: "BOTSWANA" },
  { code: "BR", name: "BRAZIL" },
  { code: "BN", name: "BRUNEI" },
  { code: "BG", name: "BULGARIA" },
  { code: "BF", name: "BURKINA FASO" },
  { code: "BI", name: "BURUNDI" },
  { code: "KH", name: "CAMBODIA" },
  { code: "CM", name: "CAMEROON" },
  { code: "CA", name: "CANADA" },
  { code: "IC", name: "CANARY ISLANDS, THE" },
  { code: "CV", name: "CAPE VERDE" },
  { code: "KY", name: "CAYMAN ISLANDS" },
  { code: "CF", name: "CENTRAL AFRICAN REPUBLIC" },
  { code: "TD", name: "CHAD" },
  { code: "CL", name: "CHILE" },
  { code: "CN", name: "CHINA, PEOPLES REPUBLIC" },
  { code: "CO", name: "COLOMBIA" },
  { code: "KM", name: "COMOROS" },
  { code: "CG", name: "CONGO" },
  { code: "CD", name: "CONGO, THE DEMOCRATIC REPUBLIC" },
  { code: "CK", name: "COOK ISLANDS" },
  { code: "CR", name: "COSTA RICA" },
  { code: "CI", name: "COTE DIVOIRE" },
  { code: "HR", name: "CROATIA" },
  { code: "CU", name: "CUBA" },
  { code: "XC", name: "CURACAO" },
  { code: "CY", name: "CYPRUS" },
  { code: "CZ", name: "CZECH REPUBLIC, THE" },
  { code: "DK", name: "DENMARK" },
  { code: "DJ", name: "DJIBOUTI" },
  { code: "DM", name: "DOMINICA" },
  { code: "DO", name: "DOMINICAN REPUBLIC" },
  { code: "TL", name: "EAST TIMOR" },
  { code: "EC", name: "ECUADOR" },
  { code: "EG", name: "EGYPT" },
  { code: "SV", name: "EL SALVADOR" },
  { code: "ER", name: "ERITREA" },
  { code: "EE", name: "ESTONIA" },
  { code: "ET", name: "ETHIOPIA" },
  { code: "FK", name: "FALKLAND ISLANDS" },
  { code: "FO", name: "FAROE ISLANDS" },
  { code: "FJ", name: "FIJI" },
  { code: "FI", name: "FINLAND" },
  { code: "FR", name: "FRANCE" },
  { code: "GF", name: "FRENCH GUYANA" },
  { code: "GA", name: "GABON" },
  { code: "GM", name: "GAMBIA" },
  { code: "GE", name: "GEORGIA" },
  { code: "DE", name: "GERMANY" },
  { code: "GH", name: "GHANA" },
  { code: "GI", name: "GIBRALTAR" },
  { code: "GR", name: "GREECE" },
  { code: "GL", name: "GREENLAND" },
  { code: "GD", name: "GRENADA" },
  { code: "GP", name: "GUADELOUPE" },
  { code: "GU", name: "GUAM" },
  { code: "GT", name: "GUATEMALA" },
  { code: "GG", name: "GUERNSEY" },
  { code: "GN", name: "GUINEA REPUBLIC" },
  { code: "GW", name: "GUINEA-BISSAU" },
  { code: "GQ", name: "GUINEA-EQUATORIAL" },
  { code: "GY", name: "GUYANA (BRITISH)" },
  { code: "HT", name: "HAITI" },
  { code: "HN", name: "HONDURAS" },
  { code: "HK", name: "HONG KONG" },
  { code: "HU", name: "HUNGARY" },
  { code: "IS", name: "ICELAND" },
  { code: "IN", name: "INDIA" },
  { code: "ID", name: "INDONESIA" },
  { code: "IR", name: "IRAN (ISLAMIC REPUBLIC OF)" },
  { code: "IQ", name: "IRAQ" },
  { code: "IE", name: "IRELAND, REPUBLIC OF" },
  { code: "IL", name: "ISRAEL" },
  { code: "IT", name: "ITALY" },
  { code: "JM", name: "JAMAICA" },
  { code: "JP", name: "JAPAN" },
  { code: "JE", name: "JERSEY" },
  { code: "JO", name: "JORDAN" },
  { code: "KZ", name: "KAZAKHSTAN" },
  { code: "KE", name: "KENYA" },
  { code: "KI", name: "KIRIBATI" },
  { code: "KR", name: "KOREA, REPUBLIC OF" },
  { code: "KP", name: "KOREA, THE D.P.R OF" },
  { code: "KV", name: "KOSOVO" },
  { code: "KW", name: "KUWAIT" },
  { code: "KG", name: "KYRGYZSTAN" },
  { code: "LA", name: "LAO PEOPLES DEMOCRATIC REPUBLIC" },
  { code: "LV", name: "LATVIA" },
  { code: "LB", name: "LEBANON" },
  { code: "LS", name: "LESOTHO" },
  { code: "LR", name: "LIBERIA" },
  { code: "LY", name: "LIBYA" },
  { code: "LI", name: "LIECHTENSTEIN" },
  { code: "LT", name: "LITHUANIA" },
  { code: "LU", name: "LUXEMBOURG" },
  { code: "MO", name: "MACAU" },
  { code: "MK", name: "MACEDONIA, REPUBLIC OF" },
  { code: "MG", name: "MADAGASCAR" },
  { code: "MW", name: "MALAWI" },
  { code: "MY", name: "MALAYSIA" },
  { code: "MV", name: "MALDIVES" },
  { code: "ML", name: "MALI" },
  { code: "MT", name: "MALTA" },
  { code: "MH", name: "MARSHALL ISLANDS" },
  { code: "MQ", name: "MARTINIQUE" },
  { code: "MR", name: "MAURITANIA" },
  { code: "MU", name: "MAURITIUS" },
  { code: "YT", name: "MAYOTTE" },
  { code: "MX", name: "MEXICO" },
  { code: "FM", name: "MICRONESIA, FEDERATED STATES OF" },
  { code: "MD", name: "MOLDOVA, REPUBLIC OF" },
  { code: "MC", name: "MONACO" },
  { code: "MN", name: "MONGOLIA" },
  { code: "ME", name: "MONTENEGRO, REPUBLIC OF" },
  { code: "MS", name: "MONTSERRAT" },
  { code: "MA", name: "MOROCCO" },
  { code: "MZ", name: "MOZAMBIQUE" },
  { code: "MM", name: "MYANMAR" },
  { code: "nan", name: "NAMIBIA" },
  { code: "NR", name: "NAURU, REPUBLIC OF" },
  { code: "NP", name: "NEPAL" },
  { code: "NL", name: "NETHERLANDS, THE" },
  { code: "XN", name: "NEVIS" },
  { code: "NC", name: "NEW CALEDONIA" },
  { code: "NZ", name: "NEW ZEALAND" },
  { code: "NI", name: "NICARAGUA" },
  { code: "NE", name: "NIGER" },
  { code: "NG", name: "NIGERIA" },
  { code: "NU", name: "NIUE" },
  { code: "NO", name: "NORWAY" },
  { code: "OM", name: "OMAN" },
  { code: "PK", name: "PAKISTAN" },
  { code: "PW", name: "PALAU" },
  { code: "PA", name: "PANAMA" },
  { code: "PG", name: "PAPUA NEW GUINEA" },
  { code: "PY", name: "PARAGUAY" },
  { code: "PE", name: "PERU" },
  { code: "PH", name: "PHILIPPINES, THE" },
  { code: "PL", name: "POLAND" },
  { code: "PT", name: "PORTUGAL" },
  { code: "PR", name: "PUERTO RICO" },
  { code: "QA", name: "QATAR" },
  { code: "RE", name: "REUNION, ISLAND OF" },
  { code: "RO", name: "ROMANIA" },
  { code: "RU", name: "RUSSIAN FEDERATION, THE" },
  { code: "RW", name: "RWANDA" },
  { code: "SH", name: "SAINT HELENA" },
  { code: "MP", name: "SAIPAN" },
  { code: "WS", name: "SAMOA" },
  { code: "SM", name: "SAN MARINO" },
  { code: "ST", name: "SAO TOME AND PRINCIPE" },
  { code: "SA", name: "SAUDI ARABIA" },
  { code: "SN", name: "SENEGAL" },
  { code: "RS", name: "SERBIA, REPUBLIC OF" },
  { code: "SC", name: "SEYCHELLES" },
  { code: "SL", name: "SIERRA LEONE" },
  { code: "SG", name: "SINGAPORE" },
  { code: "SK", name: "SLOVAKIA" },
  { code: "SI", name: "SLOVENIA" },
  { code: "SB", name: "SOLOMON ISLANDS" },
  { code: "SO", name: "SOMALIA" },
  { code: "XS", name: "SOMALILAND, REP OF (NORTH SOMALIA)" },
  { code: "ZA", name: "SOUTH AFRICA" },
  { code: "SS", name: "SOUTH SUDAN" },
  { code: "ES", name: "SPAIN" },
  { code: "LK", name: "SRI LANKA" },
  { code: "XY", name: "ST. BARTHELEMY" },
  { code: "XE", name: "ST. EUSTATIUS" },
  { code: "KN", name: "ST. KITTS" },
  { code: "LC", name: "ST. LUCIA" },
  { code: "XM", name: "ST. MAARTEN" },
  { code: "VC", name: "ST. VINCENT" },
  { code: "SD", name: "SUDAN" },
  { code: "SR", name: "SURINAME" },
  { code: "SZ", name: "SWAZILAND" },
  { code: "SE", name: "SWEDEN" },
  { code: "CH", name: "SWITZERLAND" },
  { code: "SY", name: "SYRIA" },
  { code: "PF", name: "TAHITI" },
  { code: "TW", name: "TAIWAN" },
  { code: "TJ", name: "TAJIKISTAN" },
  { code: "TZ", name: "TANZANIA" },
  { code: "TH", name: "THAILAND" },
  { code: "TG", name: "TOGO" },
  { code: "TO", name: "TONGA" },
  { code: "TT", name: "TRINIDAD AND TOBAGO" },
  { code: "TN", name: "TUNISIA" },
  { code: "TR", name: "TURKEY" },
  { code: "TM", name: "TURKMENISTAN" },
  { code: "TC", name: "TURKS AND CAICOS ISLANDS" },
  { code: "TV", name: "TUVALU" },
  { code: "UG", name: "UGANDA" },
  { code: "UA", name: "UKRAINE" },
  { code: "AE", name: "UNITED ARAB EMIRATES" },
  { code: "GB", name: "UNITED KINGDOM" },
  { code: "US", name: "UNITED STATES" },
  { code: "UY", name: "URUGUAY" },
  { code: "UZ", name: "UZBEKISTAN" },
  { code: "VU", name: "VANUATU" },
  { code: "VA", name: "VATICAN CITY STATE" },
  { code: "VE", name: "VENEZUELA" },
  { code: "VN", name: "VIETNAM" },
  { code: "VG", name: "VIRGIN ISLANDS (BRITISH)" },
  { code: "VI", name: "VIRGIN ISLANDS (US)" },
  { code: "YE", name: "YEMEN, REPUBLIC OF" },
  { code: "ZM", name: "ZAMBIA" },
  { code: "ZW", name: "ZIMBABWE" },
];

// Fast lookup: code -> name
export const COUNTRY_MAP: Record<string, string> = Object.fromEntries(
  COUNTRY_LIST.map(c => [c.code, c.name])
);

// One rule for the Rates page and BIA — see shared/corridor.ts.
export { BOOKABLE_ORIGIN, isBookableCorridor } from "@shared/corridor";